# Generated by Django 5.1.4 on 2025-05-05 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Match Date and Time')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Indicates if match has been processed')),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('curent_posses', models.PositiveIntegerField(default=0, help_text='Indicates possession: 0=None/Start, 1=Home, 2=Away')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('error', 'Error')], db_index=True, default='scheduled', max_length=20)),
                ('home_lineup', models.JSONField(blank=True, null=True)),
                ('away_lineup', models.JSONField(blank=True, null=True)),
                ('home_tactic', models.CharField(default='balanced', max_length=20)),
                ('away_tactic', models.CharField(default='balanced', max_length=20)),
                ('current_minute', models.PositiveIntegerField(default=0)),
                ('current_zone', models.CharField(choices=[('GK', 'GK'), ('DEF', 'DEF'), ('DM', 'DM'), ('MID', 'MID'), ('AM', 'AM'), ('FWD', 'FWD')], default='GK', max_length=10)),
                ('st_shoots', models.PositiveIntegerField(default=0)),
                ('st_passes', models.PositiveIntegerField(default=0)),
                ('st_possessions', models.PositiveIntegerField(default=0)),
                ('st_fouls', models.PositiveIntegerField(default=0)),
                ('st_injury', models.PositiveIntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='clubs.club')),
                ('current_player_with_ball', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_with_ball', to='players.player')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('pass', 'Pass'), ('interception', 'Interception'), ('counterattack', 'Counterattack'), ('shot_miss', 'Shot Miss'), ('foul', 'Foul'), ('injury_concern', 'Injury Concern'), ('info', 'Info'), ('match_start', 'Match Start'), ('half_time', 'Half Time'), ('match_end', 'Match End'), ('match_paused', 'Match Paused'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='players.player')),
                ('related_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_match_events', to='players.player')),
            ],
            options={
                'verbose_name': 'Match Event',
                'verbose_name_plural': 'Match Events',
                'ordering': ['timestamp'],
            },
        ),
    ]
