# Generated by Django 5.1.4 on 2025-05-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchevent',
            options={'ordering': ['match', 'minute', 'timestamp'], 'verbose_name': 'Match Event', 'verbose_name_plural': 'Match Events'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='curent_posses',
        ),
        migrations.AddField(
            model_name='match',
            name='possession_indicator',
            field=models.PositiveIntegerField(default=0, help_text='Indicates possession: 0=None/Start, 1=Home, 2=Away', verbose_name='Possession Indicator'),
        ),
        migrations.AlterField(
            model_name='match',
            name='current_player_with_ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_with_ball', to='players.player', verbose_name='Player with Ball'),
        ),
        migrations.AlterField(
            model_name='match',
            name='current_zone',
            field=models.CharField(choices=[('GK', 'GK'), ('DEF', 'DEF'), ('DM', 'DM'), ('MID', 'MID'), ('AM', 'AM'), ('FWD', 'FWD')], default='GK', max_length=10, verbose_name='Current Zone'),
        ),
        migrations.AlterField(
            model_name='match',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if match result has been processed'),
        ),
        migrations.AlterField(
            model_name='match',
            name='st_fouls',
            field=models.PositiveIntegerField(default=0, verbose_name='Fouls'),
        ),
        migrations.AlterField(
            model_name='match',
            name='st_injury',
            field=models.PositiveIntegerField(default=0, verbose_name='Injuries Count'),
        ),
        migrations.AlterField(
            model_name='match',
            name='st_passes',
            field=models.PositiveIntegerField(default=0, verbose_name='Passes'),
        ),
        migrations.AlterField(
            model_name='match',
            name='st_possessions',
            field=models.PositiveIntegerField(default=0, verbose_name='Possessions (%)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='st_shoots',
            field=models.PositiveIntegerField(default=0, verbose_name='Shoots'),
        ),
    ]
