# Generated by Django 5.1.4 on 2025-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matchevent_options_remove_match_curent_posses_and_more'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'minute'], name='matches_mat_match_i_3c5afa_idx'),
        ),
    ]
