# Generated by Django 5.0.4 on 2024-06-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('matches', '0002_teamselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamselection',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.AlterUniqueTogether(
            name='teamselection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teamselection',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_selection', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='teamselection',
            name='selection',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='match',
        ),
    ]
