# Generated by Django 5.0.1 on 2024-12-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_matchevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_minute',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
