# Generated by Django 5.1.4 on 2025-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_add_matchevent_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='current_minute',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
