# Generated by Django 5.0.4 on 2024-06-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_rename_last_updated_teamselection_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamselection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teamselection',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_selections', to='matches.match'),
        ),
    ]
