# Generated by Django 5.0.4 on 2024-06-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_teamselection_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_lineup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_lineup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TeamSelection',
        ),
    ]
