# Generated by Django 5.1.4 on 2025-02-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_add_tactic_fields'),
        ('players', '0005_player_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_player_with_ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_with_ball', to='players.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='current_zone',
            field=models.CharField(choices=[('GK', 'GK'), ('DEF', 'DEF'), ('DM', 'DM'), ('AM', 'AM'), ('FWD', 'FWD')], default='GK', max_length=10),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('pass', 'Pass'), ('interception', 'Interception'), ('shot_miss', 'Shot Miss'), ('info', 'Info'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution')], max_length=20),
        ),
    ]
