# Generated by Django 5.1.4 on 2025-05-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_current_minute'),
        ('matches', '0006_match_waiting_flag'),
    ]

    operations = [
    ]
