# Generated by Django 4.2.20 on 2025-04-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_current_player_with_ball_match_current_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='st_injury',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
