# Generated by Django 5.0.1 on 2024-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_away_lineup_match_home_lineup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.AddField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Match Date and Time'),
        ),
        migrations.AddField(
            model_name='match',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if match has been processed'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
