# Generated by Django 4.2.20 on 2025-03-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_current_player_with_ball_match_current_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='st_fouls',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_injury',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_passes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_posessions',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_shoots',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
