# Generated by Django 4.2.20 on 2025-04-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
