# Generated by Django 5.1.4 on 2025-04-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_st_fouls_match_st_passes_match_st_posessions_and_more'),
    ]

    operations = [
    ]
