# Generated by Django 5.1.4 on 2025-04-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_st_fouls_match_st_passes_match_st_posessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='curent_posses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_fouls',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_passes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_posessions',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_shoots',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
