# Generated by Django 5.1.4 on 2025-04-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20250428_0450'),
    ]

    operations = [
    ]
