# Generated by Django 5.1.4 on 2025-05-04 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    # Зависимости остаются как были сгенерированы
    dependencies = [
        ('matches', '0010_auto_20250428_1538'),
        ('players', '0006_player_morale'), # Оставляем зависимость от players, если она нужна
    ]

    operations = [
        # --- ОПЕРАЦИИ, КОТОРЫЕ ОСТАВЛЯЕМ ---
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-datetime'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchevent',
            options={'ordering': ['timestamp'], 'verbose_name': 'Match Event', 'verbose_name_plural': 'Match Events'},
        ),
        # Добавляем ТОЛЬКО НОВЫЕ поля для MatchEvent
        migrations.AddField(
            model_name='matchevent',
            name='related_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_match_events', to='players.player'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='timestamp',
            # Убираем default, который нужен был только для makemigrations
            field=models.DateTimeField(auto_now_add=True, db_index=True), 
            preserve_default=False, # Эта строка важна при удалении default
        ),
        # Оставляем все операции AlterField, так как они меняют атрибуты существующих полей
        migrations.AlterField(
            model_name='match',
            name='current_zone',
            field=models.CharField(choices=[('GK', 'GK'), ('DEF', 'DEF'), ('DM', 'DM'), ('MID', 'MID'), ('AM', 'AM'), ('FWD', 'FWD')], default='GK', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='st_injury',
            field=models.PositiveIntegerField(default=0), # Предполагаем, что это поле уже было, меняем только атрибуты
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('error', 'Error')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('pass', 'Pass'), ('interception', 'Interception'), ('shot_miss', 'Shot Miss'), ('foul', 'Foul'), ('injury_concern', 'Injury Concern'), ('info', 'Info'), ('match_start', 'Match Start'), ('half_time', 'Half Time'), ('match_end', 'Match End'), ('match_paused', 'Match Paused'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='players.player'),
        ),
        
        # --- УДАЛЕНЫ ОПЕРАЦИИ AddField ДЛЯ СУЩЕСТВУЮЩИХ ПОЛЕЙ Match ---
        # migrations.AddField(
        #     model_name='match',
        #     name='curent_posses', 
        #     ... # УДАЛЕНО
        # ),
        # migrations.AddField(
        #     model_name='match',
        #     name='st_fouls',
        #     ... # УДАЛЕНО
        # ),
        # migrations.AddField(
        #     model_name='match',
        #     name='st_passes',
        #     ... # УДАЛЕНО
        # ),
        # migrations.AddField(
        #     model_name='match',
        #     name='st_possessions',
        #     ... # УДАЛЕНО
        # ),
        # migrations.AddField(
        #     model_name='match',
        #     name='st_shoots',
        #     ... # УДАЛЕНО
        # ),
        # ----------------------------------------------------------------
    ]