# Generated by Django 5.1.4 on 2025-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20250428_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='st_fouls',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_passes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_posessions',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='st_shoots',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
