# Generated by Django 5.1.4 on 2025-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_match_options_alter_matchevent_options_and_more'),
    ]

    operations = [
    
    ]
