# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_characterevolution_narrativeevent_playerrivalry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='personality_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]