# Generated by Django 5.1.4 on 2025-10-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_match_realtime_broadcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='minute_building',
        ),
        migrations.RemoveField(
            model_name='match',
            name='realtime_last_broadcast_minute',
        ),
        migrations.RemoveField(
            model_name='match',
            name='realtime_started_at',
        ),
        migrations.DeleteModel(
            name='MatchBroadcastEvent',
        ),
    ]
