# Generated by Django 5.0.4 on 2024-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Порядковый номер сезона', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='max_teams',
            field=models.PositiveIntegerField(default=16),
        ),
    ]
