# Generated by Django 5.0.4 on 2024-11-15 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_season_number_alter_league_max_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='match_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Match start time (UTC)'),
        ),
    ]
