# Generated by Django 5.1.4 on 2024-12-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tokens',
            field=models.PositiveIntegerField(default=0, help_text='Current balance of tokens for user.'),
        ),
    ]
