# Generated by Django 5.1.4 on 2025-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.PositiveIntegerField(default=1000, help_text='Current balance of in-game money for user.'),
        ),
    ]
