# Generated by Django 5.1.4 on 2025-03-19 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_initial'),
        ('players', '0005_player_command'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_fee', models.PositiveIntegerField()),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='clubs.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='players.player')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='tournaments.season')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Transfer History',
                'verbose_name_plural': 'Transfer History',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.PositiveIntegerField()),
                ('listed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_listings', to='clubs.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_listings', to='players.player')),
            ],
            options={
                'verbose_name': 'Transfer Listing',
                'verbose_name_plural': 'Transfer Listings',
                'ordering': ['-listed_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('bidding_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_offers', to='clubs.club')),
                ('transfer_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='transfers.transferlisting')),
            ],
            options={
                'verbose_name': 'Transfer Offer',
                'verbose_name_plural': 'Transfer Offers',
                'ordering': ['-bid_amount', '-created_at'],
            },
        ),
    ]
