# Generated by Django 5.0.4 on 2024-10-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_lineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='Indicates if this team is controlled by AI', verbose_name='Bot Team'),
        ),
    ]
