# Generated by Django 5.0.4 on 2024-11-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_owner'),
        ('tournaments', '0002_season_number_alter_league_max_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='tournaments.league'),
        ),
    ]
