# Generated by Django 5.0.4 on 2024-11-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='promoted',
            field=models.BooleanField(default=False, help_text='Команда повышена в классе'),
        ),
        migrations.AddField(
            model_name='club',
            name='relegated',
            field=models.BooleanField(default=False, help_text='Команда понижена в классе'),
        ),
    ]
