# Generated by Django 5.0.1 on 2024-12-07 04:02

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(default=17, verbose_name='Age')),
                ('nationality', django_countries.fields.CountryField(default='Unknown', max_length=2, verbose_name='Nationality')),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Right Back', 'Right Back'), ('Left Back', 'Left Back'), ('Center Back', 'Center Back'), ('Defensive Midfielder', 'Central Defensive Midfielder'), ('Right Midfielder', 'Right Midfielder'), ('Central Midfielder', 'Central Midfielder'), ('Left Midfielder', 'Left Midfielder'), ('Attacking Midfielder', 'Attacking Midfielder'), ('Center Forward', 'Center Forward')], default='Unknown', max_length=50, verbose_name='Position')),
                ('player_class', models.IntegerField(default=1, verbose_name='Player Class')),
                ('strength', models.IntegerField(default=0, verbose_name='Strength')),
                ('stamina', models.IntegerField(default=0, verbose_name='Stamina')),
                ('pace', models.IntegerField(default=0, verbose_name='Pace')),
                ('positioning', models.IntegerField(default=0, verbose_name='Positioning')),
                ('reflexes', models.IntegerField(default=0, verbose_name='Reflexes')),
                ('handling', models.IntegerField(default=0, verbose_name='Handling')),
                ('aerial', models.IntegerField(default=0, verbose_name='Aerial')),
                ('command', models.IntegerField(default=0, verbose_name='Command')),
                ('distribution', models.IntegerField(default=0, verbose_name='Distribution')),
                ('one_on_one', models.IntegerField(default=0, verbose_name='One on One')),
                ('rebound_control', models.IntegerField(default=0, verbose_name='Rebound Control')),
                ('shot_reading', models.IntegerField(default=0, verbose_name='Shot Reading')),
                ('marking', models.IntegerField(default=0, verbose_name='Marking')),
                ('tackling', models.IntegerField(default=0, verbose_name='Tackling')),
                ('work_rate', models.IntegerField(default=0, verbose_name='Work Rate')),
                ('passing', models.IntegerField(default=0, verbose_name='Passing')),
                ('crossing', models.IntegerField(default=0, verbose_name='Crossing')),
                ('dribbling', models.IntegerField(default=0, verbose_name='Dribbling')),
                ('flair', models.IntegerField(default=0, verbose_name='Flair')),
                ('heading', models.IntegerField(default=0, verbose_name='Heading')),
                ('finishing', models.IntegerField(default=0, verbose_name='Finishing')),
                ('long_range', models.IntegerField(default=0, verbose_name='Long Range')),
                ('vision', models.IntegerField(default=0, verbose_name='Vision')),
                ('accuracy', models.IntegerField(default=0, verbose_name='Accuracy')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
