# Generated by Django 5.0.1 on 2024-12-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='experience',
            field=models.FloatField(default=0.0, verbose_name='Experience'),
        ),
    ]
