# Generated by Django 5.0.4 on 2024-05-07 16:24

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aerial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aerial'),
        ),
        migrations.AddField(
            model_name='player',
            name='ball_control',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ball Control'),
        ),
        migrations.AddField(
            model_name='player',
            name='command',
            field=models.IntegerField(blank=True, null=True, verbose_name='Command'),
        ),
        migrations.AddField(
            model_name='player',
            name='crossing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Crossing'),
        ),
        migrations.AddField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dribbling'),
        ),
        migrations.AddField(
            model_name='player',
            name='finishing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Finishing'),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='player',
            name='handling',
            field=models.IntegerField(blank=True, null=True, verbose_name='Handling'),
        ),
        migrations.AddField(
            model_name='player',
            name='heading',
            field=models.IntegerField(blank=True, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='player',
            name='jumping',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumping'),
        ),
        migrations.AddField(
            model_name='player',
            name='kicking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kicking'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='player',
            name='long_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Long Range'),
        ),
        migrations.AddField(
            model_name='player',
            name='marking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marking'),
        ),
        migrations.AddField(
            model_name='player',
            name='pace',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pace'),
        ),
        migrations.AddField(
            model_name='player',
            name='passing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Passing'),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Right Back', 'Right Back'), ('Left Back', 'Left Back'), ('Center Back', 'Center Back'), ('Defensive Midfielder', 'Central Defensive Midfielder'), ('Left Defensive Midfielder', 'Left Defensive Midfielder'), ('Right Defensive Midfielder', 'Right Defensive Midfielder'), ('Right Midfielder', 'Right Midfielder'), ('Central Midfielder', 'Central Midfielder'), ('Left Midfielder', 'Left Midfielder'), ('Attacking Midfielder', 'Attacking Midfielder'), ('Center Forward', 'Center Forward')], default='Unknown', max_length=50, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='positioning',
            field=models.IntegerField(blank=True, null=True, verbose_name='Positioning'),
        ),
        migrations.AddField(
            model_name='player',
            name='reflexes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reflexes'),
        ),
        migrations.AddField(
            model_name='player',
            name='stamina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stamina'),
        ),
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.IntegerField(blank=True, null=True, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='player',
            name='tackling',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tackling'),
        ),
        migrations.AddField(
            model_name='player',
            name='throwing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Throwing'),
        ),
        migrations.AddField(
            model_name='player',
            name='vision',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vision'),
        ),
        migrations.AddField(
            model_name='player',
            name='work_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Work Rate'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=django_countries.fields.CountryField(default='Unknown', max_length=2, verbose_name='Nationality'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('first_name', 'last_name')},
        ),
    ]
