# Generated by Django 5.1.4 on 2025-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='base_morale',
            field=models.IntegerField(default=50, help_text='Базовый уровень морали, к которому стремится текущая мораль', verbose_name='Base Morale'),
        ),
    ]
