# Generated by Django 5.0.4 on 2024-06-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_aerial_player_ball_control_player_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_class',
            field=models.IntegerField(default=1, verbose_name='Player Class'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aerial',
            field=models.IntegerField(default=0, verbose_name='Aerial'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ball_control',
            field=models.IntegerField(default=0, verbose_name='Ball Control'),
        ),
        migrations.AlterField(
            model_name='player',
            name='command',
            field=models.IntegerField(default=0, verbose_name='Command'),
        ),
        migrations.AlterField(
            model_name='player',
            name='crossing',
            field=models.IntegerField(default=0, verbose_name='Crossing'),
        ),
        migrations.AlterField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(default=0, verbose_name='Dribbling'),
        ),
        migrations.AlterField(
            model_name='player',
            name='finishing',
            field=models.IntegerField(default=0, verbose_name='Finishing'),
        ),
        migrations.AlterField(
            model_name='player',
            name='handling',
            field=models.IntegerField(default=0, verbose_name='Handling'),
        ),
        migrations.AlterField(
            model_name='player',
            name='heading',
            field=models.IntegerField(default=0, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jumping',
            field=models.IntegerField(default=0, verbose_name='Jumping'),
        ),
        migrations.AlterField(
            model_name='player',
            name='kicking',
            field=models.IntegerField(default=0, verbose_name='Kicking'),
        ),
        migrations.AlterField(
            model_name='player',
            name='long_range',
            field=models.IntegerField(default=0, verbose_name='Long Range'),
        ),
        migrations.AlterField(
            model_name='player',
            name='marking',
            field=models.IntegerField(default=0, verbose_name='Marking'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pace',
            field=models.IntegerField(default=0, verbose_name='Pace'),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.IntegerField(default=0, verbose_name='Passing'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positioning',
            field=models.IntegerField(default=0, verbose_name='Positioning'),
        ),
        migrations.AlterField(
            model_name='player',
            name='reflexes',
            field=models.IntegerField(default=0, verbose_name='Reflexes'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stamina',
            field=models.IntegerField(default=0, verbose_name='Stamina'),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=0, verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tackling',
            field=models.IntegerField(default=0, verbose_name='Tackling'),
        ),
        migrations.AlterField(
            model_name='player',
            name='throwing',
            field=models.IntegerField(default=0, verbose_name='Throwing'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vision',
            field=models.IntegerField(default=0, verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='player',
            name='work_rate',
            field=models.IntegerField(default=0, verbose_name='Work Rate'),
        ),
    ]
