# Generated by Django 5.1.4 on 2024-12-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='boost_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this player was boosted via tokens.'),
        ),
    ]
