# Generated by Django 5.0.4 on 2024-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_player_class_alter_player_aerial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='ball_control',
        ),
        migrations.RemoveField(
            model_name='player',
            name='jumping',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kicking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='throwing',
        ),
        migrations.AddField(
            model_name='player',
            name='accuracy',
            field=models.IntegerField(default=0, verbose_name='Accuracy'),
        ),
        migrations.AddField(
            model_name='player',
            name='distribution',
            field=models.IntegerField(default=0, verbose_name='Distribution'),
        ),
        migrations.AddField(
            model_name='player',
            name='flair',
            field=models.IntegerField(default=0, verbose_name='Flair'),
        ),
        migrations.AddField(
            model_name='player',
            name='one_on_one',
            field=models.IntegerField(default=0, verbose_name='One on One'),
        ),
        migrations.AddField(
            model_name='player',
            name='rebound_control',
            field=models.IntegerField(default=0, verbose_name='Rebound Control'),
        ),
        migrations.AddField(
            model_name='player',
            name='shot_reading',
            field=models.IntegerField(default=0, verbose_name='Shot Reading'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Right Back', 'Right Back'), ('Left Back', 'Left Back'), ('Center Back', 'Center Back'), ('Defensive Midfielder', 'Central Defensive Midfielder'), ('Right Midfielder', 'Right Midfielder'), ('Central Midfielder', 'Central Midfielder'), ('Left Midfielder', 'Left Midfielder'), ('Attacking Midfielder', 'Attacking Midfielder'), ('Center Forward', 'Center Forward')], default='Unknown', max_length=50, verbose_name='Position'),
        ),
    ]
