# Generated by Django 5.1.4 on 2025-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_bloom_seasons_left_player_bloom_start_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='personality_traits',
            field=models.JSONField(blank=True, default=dict, help_text='Player personality traits for the Narrative AI Engine'),
        ),
    ]
