# Generated by Django 5.1.4 on 2025-01-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='command',
            field=models.IntegerField(default=0, verbose_name='Command'),
        ),
    ]
