# Generated by Django 4.2.20 on 2025-03-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='morale',
            field=models.IntegerField(default=0, verbose_name='Morale'),
        ),
    ]
